baseURL: "/"
languageCode: en-us
title: Lawrence Lim
theme: PaperMod

languages:
  en:
    languageName: ":en:"
    contentDir: 'content/en'
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: About
          url: about/
          weight: 2
        - name: Projects
          url: project/
          weight: 3
        - name: Articles
          url: article/
          weight: 4
        - name: Contact
          url: contact/

  ä¸­æ–‡:
    languageName: ":zh:"
    contentDir: 'content/zh'
    weight: 2
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: ä¸»é¡µ
          url: ä¸­æ–‡/
          weight: 1
        - name: å…³äº
          url: about/
          weight: 2
        - name: é¡¹ç›®
          url: project/
          weight: 3
        - name: æ–‡ç« 
          url: article/
          weight: 4
        - name: è”ç³»
          url: contact/
params:
  profileMode:
    enabled: true
    title: "Lawrence Lim - æ—ç¿éª"
    subtitle: "ğŸ‘· Web 3 Builder | ğŸ’» CS Student | ğŸ“š NYU Shanghai"
    imageUrl: "img/ll_profile_pic.jpg"
    imageTitle: "Image Unavailable"
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: Contact Me
        url: "/contact"
      - name: Github
        url: "https://github.com/larry-lime"

  socialIcons:
    - name: email
      url: "mailto:ll4715@nyu.edu"
    - name: twitter
      url: "https://twitter.com/lawrence_lim__"
    - name: github
      url: "https://github.com/larry-lime"
    - name: linkedin
      url: "https://www.linkedin.com/in/lawrence-rx-lim/"
    - name: telegram
      url: "https://t.me/larrylime4132"

  cover:
    linkFullImages: true

  assets:
    favicon: "img/favicon.ico"
    favicon16x16: "img/favicon-16x16.png"
    favicon32x32: "img/favicon-32x32.png"
